name: 🚀 Build & Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout repository
        uses: actions/checkout@v4

      - name: 🏗️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔑 Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🏷️ Extract Git commit SHA
        id: git_info
        run: echo "SHA_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: 🏗️ Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/meeting-summarizer:${{ steps.git_info.outputs.SHA_TAG }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/meeting-summarizer:${{ steps.git_info.outputs.SHA_TAG }} ${{ secrets.DOCKER_USERNAME }}/meeting-summarizer:latest

      - name: 🚀 Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/meeting-summarizer:${{ steps.git_info.outputs.SHA_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/meeting-summarizer:latest
